# GET http://localhost:3000/user/list HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyayIsImVtYWlsIjoiMTM5NzIzMzM3NjVAMTM5LmNvbSIsImlhdCI6MTcxMTQ2MDI3MCwiZXhwIjoxNzEyMDY1MDcwfQ.1GqZ-KBR9a7NS5-H5eX7BokyjNmyByAgP392GS62sLQ

# POST http://localhost:3000/user/create HTTP/1.1
# Content-Type: application/json


# {
#     "name": "Mark",
#     "email": "13972333765@139.com"
# }

POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json


{
    "name": "Mark",
    "email": "13972333765@139.com"
}